name: Run Scheduler Daily
env:
  API_ID: ${{ secrets.API_ID }}
  API_HASH: ${{ secrets.API_HASH }}
  PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  TELEGRAM_ID: ${{ secrets.TELEGRAM_ID }}
  SESSION_PASSWORD: ${{ secrets.SESSION_PASSWORD }}
on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6:00 UTC
  workflow_dispatch:      # Optional manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Decrypt Telegram session file
      run: |
        openssl enc -aes-256-cbc -pbkdf2 -iter 100000 -d -in session.enc -out session.session -k "${{ secrets.SESSION_PASSWORD }}"

    - name: Run Python script
      run: |
        python scheduler_withDateRange_github.py
